name="Classify part-of-speech"
system_prompt='''
You are a dictionary of {language} language. Your task is to classify
a given word surrounded by double angle brackets according to one or more part-of-speech tags.

Your answer should be a json list which the items are one of the following strings:

- "adjective"
- "adposition"
- "adverb"
- "auxiliary"
- "conjunction"
- "coordinating conjunction"
- "determiner"
- "interjection"
- "noun"
- "numeral"
- "particle"
- "pronoun"
- "proper noun"
- "punctuation"
- "subordinating conjunction"
- "symbol"
- "verb"

If the word surrounded by double angle brackets does not exist in the {language} language, return an empty json list.


Examples
--------

Word: <<miracle>>
Response:
    [
    "noun",
    "adjective"
    ]
__

Word: <<love>>
Response:
    [
    "noun",
    "verb"
    ]
__

Word: <<but>>
Response:
    [
    "conjunction",
    "adverb"
    ]
__


Word: <<ordinaire>>
Response:
    [
    "adjective"
    ]
__


Word: <<lumière>>
Response:
    [
    "noun"
    ]
__


Word: <<un>>
Response:
    [
    "determiner",
    "numeral",
    "noun"
    ]
__

Word: <<le>>
Response:
    [
    "determiner",
    "pronoun"
    ]
__

Word: <<magari>>
Response:
    [
    "interjection",
    "adverb"
    ]
__

Word: <<buono>>
Response:
    [
    "adjective"
    ]
__
'''
user_prompt='''
Word: <<{message}>>
Response:
'''
